[Variables]

; --- PROGRESS BAR
orientation_progressbar=Vertical
width_progressbar=2
height_progressbar=100
xpos_progressbar=448
ypos_progressbar=12

; --- NOW
xpos_now=458
ypos_now=44

; --- PLAYING
xpos_playing=458
ypos_playing=58

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=276
ypos_nowplaying=18

; --- UPDATE INDICATOR
xpos_indicator=504
ypos_indicator=47

; --- TIME
xpos_time=458
ypos_time=14

; --- PROGRESS
xpos_progress=458
ypos_progress=26

; --- SETTINGS
xpos_settings=486
ypos_settings=26

; --- PLAY BUTTON
xpos_play=492
ypos_play=94

; --- PREVIOUS BUTTON
xpos_prev=458
ypos_prev=80

; --- NEXT BUTTON
xpos_next=458
ypos_next=94

; --- INTERFACE
align_interface=Left

; --- REGULAR: CONTAINERS
xpos_container_reg=4
ypos_containertop_reg=22
ypos_containerbtm_reg=57
width_container_reg=435

; --- STANDARD: CONTAINERS
width_container_std=435
width_container_scroll=512
height_container_std=44

; --- CONTAINER TEXT
xpos_containertext=436
ypos_containertextbtm=0
ypos_containertexttop=48
align_containertext_supposed=Right

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=437

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=18
pure_ypos_containerbtm_reg=53
