[Variables]

skinSize=400
lastSetWidth=450

Player=Spotify
alignRight=1

activePlugin=NowPlaying

topTextWidth=147
bottomTextWidth=363

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=Spotify (NowPlaying)
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=1

removeExtraFromText=1

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=450
mediaTextAlignment=RightBottom
mediaTextAlignmentPure=Right
interfaceTextAlignment=Left
nowTextPositionHor=517.5
hairlinePositionHor=504
topTextPositionHor=490.5
playCtrlPositionHor=555.75
settingsTextPositionHor=551.25
indicatorPositionHor=569.25
indicatorPositionHorPure=436.5
conflictIndicatorPositionHor=544.5
conflictIndicatorPositionHorPure=418.5
