[0]
Meter=String
MeterStyle=s
Text=Default
LeftMouseDownAction=[!SetVariable AudioDeviceID "" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "" "C:\Users\Max.Harrison\source\personal\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Default" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=Speakers (High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{212b75c4-3811-4f8d-a239-1b617ada8cf2}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{212b75c4-3811-4f8d-a239-1b617ada8cf2}" "C:\Users\Max.Harrison\source\personal\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Speakers (High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=Speakers (High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{40739e20-4927-4e33-a16f-044186947f7f}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{40739e20-4927-4e33-a16f-044186947f7f}" "C:\Users\Max.Harrison\source\personal\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Speakers (High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[3]
Meter=String
MeterStyle=s
Text=Headphones (EarFun Air Stereo)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{4eb5c7ed-0b4e-493b-8f2a-e58fcebeb17d}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{4eb5c7ed-0b4e-493b-8f2a-e58fcebeb17d}" "C:\Users\Max.Harrison\source\personal\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Headphones (EarFun Air Stereo)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[4]
Meter=String
MeterStyle=s
Text=Headset (EarFun Air Hands-Free AG Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{f7177d1d-0788-45fd-9fff-71b84b37987e}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{f7177d1d-0788-45fd-9fff-71b84b37987e}" "C:\Users\Max.Harrison\source\personal\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Headset (EarFun Air Hands-Free AG Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
