[0]
Meter=String
MeterStyle=s
Text=Default
LeftMouseDownAction=[!SetVariable AudioDeviceID "" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "" "c:\users\max.harrison\source\personal\rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Default" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=AMD HDMI Output (AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{84caaaae-a43f-4734-aa24-b0e37ec793f8}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{84caaaae-a43f-4734-aa24-b0e37ec793f8}" "c:\users\max.harrison\source\personal\rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "AMD HDMI Output (AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=PC Speakers (Realtek High Definition Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{ef594f06-3e8a-4610-8007-16447737e7e2}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{ef594f06-3e8a-4610-8007-16447737e7e2}" "c:\users\max.harrison\source\personal\rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "PC Speakers (Realtek High Definition Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
